### ISSUE TITLE
General task list

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/foss4g2022_grass4rs#1]
- [x] Prepare S2 data for NC location, proposed computational region: same as landsat scenes
- [x] Decide on exercises/steps to show
- [x] Obtain new land use land cover data for NC (osm?)
- [x] Create a merge between neteler's and vero's notebooks
